services:
  serve:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: game-of-life
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - 80:80
    volumes:
      - .:/app

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    container_name: game-of-life
    command: >
      sh -c "npm run dev"
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./package.json
          action: rebuild
    volumes:
      - ./src/:/app/src/

  node-build:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    container_name: game-of-life
    command: >
      sh -c "npm run build"
    volumes:
      - .:/app
