services:
  dev:
    build: .
    container_name: game-of-life
    command: ["nginx", "-g", "daemon off;"]
    ports:
      - 80:80
    volumes:
      - .:/app

  node-build:
    image: node:18-alpine3.17
    working_dir: /app
    container_name: game-of-life
    command: >
      sh -c "npm install && npm run build"
    volumes:
      - .:/app
